name: Update README cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
# 添加权限配置
permissions:
  contents: write  # 赋予写入仓库的权限
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 在 GitHub Actions 中生成卡片时设置相同的高度参数
      - name: Generate stats card
        run: |
          curl -o profile/stats.svg \
            "https://github-readme-stats.vercel.app/api?username=${{ github.repository_owner }}&show_icons=true&theme=radical&hide_border=true&line_height=28&card_width=243&title_color=fab005&text_color=fff9db&icon_color=fab005&rank_icon=percentile&bg_color=00000000&include_all_commits=true&hide_title=true"
      
      - name: Generate top languages card
        run: |
          curl -o profile/top-langs.svg \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=${{ github.repository_owner }}&theme=radical&langs_count=10&hide_border=true&line_height=28&card_width=243&title_color=fab005&text_color=fff9db&icon_color=fab005&hide_title=true"
      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || exit 0
          git push
